package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseExhibitionElement<M extends BaseExhibitionElement<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setExhibitionid(java.lang.Integer exhibitionid) {
		set("exhibitionid", exhibitionid);
		return (M)this;
	}
	
	public java.lang.Integer getExhibitionid() {
		return getInt("exhibitionid");
	}

	public M setElementsubtitle(java.lang.String elementsubtitle) {
		set("elementsubtitle", elementsubtitle);
		return (M)this;
	}
	
	public java.lang.String getElementsubtitle() {
		return getStr("elementsubtitle");
	}

	public M setElementname(java.lang.String elementname) {
		set("elementname", elementname);
		return (M)this;
	}
	
	public java.lang.String getElementname() {
		return getStr("elementname");
	}

	public M setImgpath(java.lang.String imgpath) {
		set("imgpath", imgpath);
		return (M)this;
	}
	
	public java.lang.String getImgpath() {
		return getStr("imgpath");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setGoodsid(java.lang.Integer goodsid) {
		set("goodsid", goodsid);
		return (M)this;
	}
	
	public java.lang.Integer getGoodsid() {
		return getInt("goodsid");
	}

	public M setLink(java.lang.String link) {
		set("link", link);
		return (M)this;
	}
	
	public java.lang.String getLink() {
		return getStr("link");
	}

	public M setSort(java.lang.Integer sort) {
		set("sort", sort);
		return (M)this;
	}
	
	public java.lang.Integer getSort() {
		return getInt("sort");
	}

	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}
	
	public java.lang.Integer getState() {
		return getInt("state");
	}

	public M setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
		return (M)this;
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public M setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
		return (M)this;
	}
	
	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

	public M setCreateby(java.lang.Integer createby) {
		set("createby", createby);
		return (M)this;
	}
	
	public java.lang.Integer getCreateby() {
		return getInt("createby");
	}

	public M setUpdateby(java.lang.Integer updateby) {
		set("updateby", updateby);
		return (M)this;
	}
	
	public java.lang.Integer getUpdateby() {
		return getInt("updateby");
	}

	public M setDeletestatus(java.lang.Integer deletestatus) {
		set("deletestatus", deletestatus);
		return (M)this;
	}
	
	public java.lang.Integer getDeletestatus() {
		return getInt("deletestatus");
	}

}
