package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseShopNotices<M extends BaseShopNotices<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setShopid(java.lang.Integer shopid) {
		set("shopid", shopid);
		return (M)this;
	}
	
	public java.lang.Integer getShopid() {
		return getInt("shopid");
	}

	public M setNoticetitile(java.lang.String noticetitile) {
		set("noticetitile", noticetitile);
		return (M)this;
	}
	
	public java.lang.String getNoticetitile() {
		return getStr("noticetitile");
	}

	public M setNoticecontent(java.lang.String noticecontent) {
		set("noticecontent", noticecontent);
		return (M)this;
	}
	
	public java.lang.String getNoticecontent() {
		return getStr("noticecontent");
	}

	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}
	
	public java.lang.Integer getState() {
		return getInt("state");
	}

	public M setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
		return (M)this;
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public M setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
		return (M)this;
	}
	
	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

	public M setCreateby(java.lang.Integer createby) {
		set("createby", createby);
		return (M)this;
	}
	
	public java.lang.Integer getCreateby() {
		return getInt("createby");
	}

	public M setUpdateby(java.lang.Integer updateby) {
		set("updateby", updateby);
		return (M)this;
	}
	
	public java.lang.Integer getUpdateby() {
		return getInt("updateby");
	}

	public M setDeletestatus(java.lang.Integer deletestatus) {
		set("deletestatus", deletestatus);
		return (M)this;
	}
	
	public java.lang.Integer getDeletestatus() {
		return getInt("deletestatus");
	}

}
