package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAptitude<M extends BaseAptitude<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setShopid(java.lang.Integer shopid) {
		set("shopid", shopid);
		return (M)this;
	}
	
	public java.lang.Integer getShopid() {
		return getInt("shopid");
	}

	public M setAptitudename(java.lang.String aptitudename) {
		set("aptitudename", aptitudename);
		return (M)this;
	}
	
	public java.lang.String getAptitudename() {
		return getStr("aptitudename");
	}

	public M setPictureurl(java.lang.String pictureurl) {
		set("pictureurl", pictureurl);
		return (M)this;
	}
	
	public java.lang.String getPictureurl() {
		return getStr("pictureurl");
	}

	public M setPublicstatus(java.lang.Integer publicstatus) {
		set("publicstatus", publicstatus);
		return (M)this;
	}
	
	public java.lang.Integer getPublicstatus() {
		return getInt("publicstatus");
	}

	public M setAptituderemark(java.lang.String aptituderemark) {
		set("aptituderemark", aptituderemark);
		return (M)this;
	}
	
	public java.lang.String getAptituderemark() {
		return getStr("aptituderemark");
	}

	public M setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
		return (M)this;
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public M setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
		return (M)this;
	}
	
	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

	public M setCreateby(java.lang.Integer createby) {
		set("createby", createby);
		return (M)this;
	}
	
	public java.lang.Integer getCreateby() {
		return getInt("createby");
	}

	public M setUpdateby(java.lang.Integer updateby) {
		set("updateby", updateby);
		return (M)this;
	}
	
	public java.lang.Integer getUpdateby() {
		return getInt("updateby");
	}

	public M setDeletestatus(java.lang.Integer deletestatus) {
		set("deletestatus", deletestatus);
		return (M)this;
	}
	
	public java.lang.Integer getDeletestatus() {
		return getInt("deletestatus");
	}

}
