package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseShopinfo<M extends BaseShopinfo<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setCustomerid(java.lang.Integer customerid) {
		set("customerid", customerid);
		return (M)this;
	}
	
	public java.lang.Integer getCustomerid() {
		return getInt("customerid");
	}

	public M setShuihao(java.lang.String shuihao) {
		set("shuihao", shuihao);
		return (M)this;
	}
	
	public java.lang.String getShuihao() {
		return getStr("shuihao");
	}

	public M setYingyezhizhaohao(java.lang.String yingyezhizhaohao) {
		set("yingyezhizhaohao", yingyezhizhaohao);
		return (M)this;
	}
	
	public java.lang.String getYingyezhizhaohao() {
		return getStr("yingyezhizhaohao");
	}

	public M setDeposit(java.math.BigDecimal deposit) {
		set("deposit", deposit);
		return (M)this;
	}
	
	public java.math.BigDecimal getDeposit() {
		return get("deposit");
	}

	public M setCompanyname(java.lang.String companyname) {
		set("companyname", companyname);
		return (M)this;
	}
	
	public java.lang.String getCompanyname() {
		return getStr("companyname");
	}

	public M setCompanyurl(java.lang.String companyurl) {
		set("companyurl", companyurl);
		return (M)this;
	}
	
	public java.lang.String getCompanyurl() {
		return getStr("companyurl");
	}

	public M setProvince(java.lang.String province) {
		set("province", province);
		return (M)this;
	}
	
	public java.lang.String getProvince() {
		return getStr("province");
	}

	public M setCity(java.lang.String city) {
		set("city", city);
		return (M)this;
	}
	
	public java.lang.String getCity() {
		return getStr("city");
	}

	public M setArea(java.lang.String area) {
		set("area", area);
		return (M)this;
	}
	
	public java.lang.String getArea() {
		return getStr("area");
	}

	public M setRegistaddress(java.lang.String registaddress) {
		set("registaddress", registaddress);
		return (M)this;
	}
	
	public java.lang.String getRegistaddress() {
		return getStr("registaddress");
	}

	public M setTelephone(java.lang.String telephone) {
		set("telephone", telephone);
		return (M)this;
	}
	
	public java.lang.String getTelephone() {
		return getStr("telephone");
	}

	public M setFax(java.lang.String fax) {
		set("fax", fax);
		return (M)this;
	}
	
	public java.lang.String getFax() {
		return getStr("fax");
	}

	public M setCompanyabstract(java.lang.String companyabstract) {
		set("companyabstract", companyabstract);
		return (M)this;
	}
	
	public java.lang.String getCompanyabstract() {
		return getStr("companyabstract");
	}

	public M setMainproducts(java.lang.String mainproducts) {
		set("mainproducts", mainproducts);
		return (M)this;
	}
	
	public java.lang.String getMainproducts() {
		return getStr("mainproducts");
	}

	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}
	
	public java.lang.Integer getState() {
		return getInt("state");
	}

	public M setPasstime(java.util.Date passtime) {
		set("passtime", passtime);
		return (M)this;
	}
	
	public java.util.Date getPasstime() {
		return get("passtime");
	}

	public M setAuditor(java.lang.Integer auditor) {
		set("auditor", auditor);
		return (M)this;
	}
	
	public java.lang.Integer getAuditor() {
		return getInt("auditor");
	}

	public M setLogoimg(java.lang.String logoimg) {
		set("logoimg", logoimg);
		return (M)this;
	}
	
	public java.lang.String getLogoimg() {
		return getStr("logoimg");
	}

	public M setLicenseimg(java.lang.String licenseimg) {
		set("licenseimg", licenseimg);
		return (M)this;
	}
	
	public java.lang.String getLicenseimg() {
		return getStr("licenseimg");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
		return (M)this;
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public M setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
		return (M)this;
	}
	
	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

	public M setCreateby(java.lang.Integer createby) {
		set("createby", createby);
		return (M)this;
	}
	
	public java.lang.Integer getCreateby() {
		return getInt("createby");
	}

	public M setUpdateby(java.lang.Integer updateby) {
		set("updateby", updateby);
		return (M)this;
	}
	
	public java.lang.Integer getUpdateby() {
		return getInt("updateby");
	}

}
