package com.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSearchRecord<M extends BaseSearchRecord<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setSearchcontent(java.lang.String searchcontent) {
		set("searchcontent", searchcontent);
		return (M)this;
	}
	
	public java.lang.String getSearchcontent() {
		return getStr("searchcontent");
	}

	public M setNumber(java.lang.Integer number) {
		set("number", number);
		return (M)this;
	}
	
	public java.lang.Integer getNumber() {
		return getInt("number");
	}

}
