package com.model;

import com.model.base.BaseExhibitionElement;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ExhibitionElement extends BaseExhibitionElement<ExhibitionElement> {
	
}
