package com.model;

import com.model.base.BasePropertyValues;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PropertyValues extends BasePropertyValues<PropertyValues> {
	
}
